<?php
/**
 * Configuration for Users CRUD Example with PostgreSQL
 */

// Enable error reporting for development
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Define base path
define('BASE_PATH', dirname(__DIR__, 3));

// Load Composer autoloader
require_once BASE_PATH . '/vendor/autoload.php';

use RapidBase\Core\DB;
use RapidBase\Core\Conn;

// Database configuration - PostgreSQL
define('DB_DRIVER', 'pgsql');
define('DB_HOST', 'localhost');
define('DB_PORT', '5432');
define('DB_NAME', 'rapidbase_test');
define('DB_USER', 'rapidbase');
define('DB_PASS', 'rapidbase123');

// Initialize database connection
$dsn = 'pgsql:host=' . DB_HOST . ';port=' . DB_PORT . ';dbname=' . DB_NAME;
DB::setup($dsn, DB_USER, DB_PASS, 'main');

// Load schema map generated by Meta Discovery
SchemaMapper::setOutputFile(BASE_PATH . '/src/RapidBase/Meta/schema_map.php');
$schemaMap = \RapidBase\Meta\SchemaMapper::loadMap();
if ($schemaMap) {
    DB::loadRelationsMap(BASE_PATH . '/src/RapidBase/Meta/schema_map.php');
}
